# Generated by Django 2.1.2 on 2018-10-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_Address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('devices', models.ForeignKey(default='No Devices', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.Device')),
            ],
        ),
    ]
