# Generated by Django 2.1.2 on 2018-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20181017_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
