# Generated by Django 2.1.2 on 2018-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20181018_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='Inventory.DeviceGroup'),
        ),
    ]
