# Generated by Django 2.1.2 on 2018-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20181019_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.ManyToManyField(blank=True, default='No Group', to='Inventory.DeviceGroup'),
        ),
    ]
