# Generated by Django 2.1.2 on 2018-10-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20181020_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.ManyToManyField(blank=True, to='Inventory.DeviceGroup'),
        ),
    ]
