# Generated by Django 2.1.2 on 2018-10-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='User',
        ),
    ]
