# Generated by Django 2.1.2 on 2018-10-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20181021_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Model',
        ),
    ]
