# Generated by Django 2.1.2 on 2018-10-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_auto_20181021_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Model',
            new_name='User',
        ),
    ]
